language: java
jdk:
  - oraclejdk11
before_install:
  - sudo apt-get update
  - cd DockerFromZeroToMastery-SpingBootAndJava/
  - echo "Let's start Maven Package!!!"
  - mvn clean package
  - cd ..
  - echo "We are in root dir"
script:
  - docker-compose build
before_deploy:
  - echo daniel100 | docker login --username danielpaulinomesquita --password-stdin
deploy:
  provider: script
  script:
    docker tag docker-from-zero-to-mastery-java:latest danielpaulinomesquita/docker-from-zero-to-mastery-java:tag2teste;
    docker push danielpaulinomesquita/docker-from-zero-to-mastery-java;
  on:
    brach: master
notifications:
  email: false
